name: Deploy AEDev Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts


      - name: Deploy frontend
        run: |
          rsync -rz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519" \
            frontend/dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/aedev.pro/frontend/


      - name: Deploy backend
        run: |
          rsync -rz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519" \
            backend/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/aedev.pro/backend/


      - name: Deploy docker-compose.yml
        run: |
          rsync -rz \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519" \
            docker-compose.yml \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/aedev.pro/


      - name: Deploy .env
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "echo '${{ secrets.ENV_FILE }}' > /var/www/html/aedev.pro/.env"


      - name: Restart backend
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "cd /var/www/html/aedev.pro && docker compose up -d --build"
